### ISSUE TITLE
Breaks between node 4.7.3 and 4.8.0

### ISSUE THREAD

**Issue by naugtur** [parro-it/spawn-shell#1]
[edit] simply put: tests are failing on node v4.8.0 and up (including 6.x 7.x)

I run a commands with some arguments:

In node v4.7.3 and earlier versions
```
spawnShell(`npm install --production --no-optional --unsafe-perm=false --prefix=${dir}`)
```
The same code breaks by calling just npm and passing all other arguments to bash instead of npm. npm prints usage information instead of installing.

To make a command work in node v4.8.0 or higher, I need to put additional quotes inside, so when passing to bash -c it works as expected.
```
spawnShell(`"npm install --production --no-optional --unsafe-perm=false --prefix=${dir}"`)
```

I'm using the latest version of spawn-shell

**Comment by parro-it** [comment]
Thank you @naugtur: please node that in node v4.8.0 or higher there is a "shell" argument in spawn method, so you can easily obtain the same effects than using this module.

It would, anyway, preferable to make it work, because one may need to support both old and newer node versions... I will do some investigation soon, thank you!
